defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: hk-movies
    values:
      section: reviews/movies/hk-movies
  - scope:
      type: jp-movies
    values:
      section: reviews/movies/jp-movies
  - scope:
      type: jackie-movies
    values:
      section: jackie
  - scope:
      type: bad-movies
    values:
      section: reviews/movies/bad-movies
  - scope:
      type: game-reviews
    values:
      section: reviews/games

collections_dir: _collections

collections:
  - jackie-movies
  - chillies
  - hk-movies
  - jp-movies
  - bad-movies
  - western-movies
  - game-reviews
