defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      category: hk-movies
    values:
      section: reviews/movies/hk-movies

collections_dir: _collections

collections:
  - jackie-movies
  - chillies
  - hk-movies
  - jp-movies
  - bad-movies
  - western-movies
  - game-reviews
